import "server-only";

import type { DesignStyle, RoomType } from "@/db/schemas/shared.schema";

/*
 * The one interface every AI image provider implements. Adding a provider = a
 * new file in this folder implementing this, then registering it in the chain
 * (registry.ts). The AI service only ever talks to this interface.
 */

export interface RedesignRequest {
  imageBytes: Buffer;
  imageMime: string;
  /** Public URL of the source image (some providers fetch by URL, not bytes). */
  imageUrl: string;
  /** Server-assembled, private redesign prompt. */
  prompt: string;
  style: DesignStyle;
  roomType: RoomType;
}

export interface RedesignResult {
  /** The generated image bytes (PNG/JPEG). */
  bytes: Buffer;
  /** The provider + model that produced it (persisted on the design). */
  provider: string;
  model: string;
  /** Provider-reported cost in USD, if known (for the generation log). */
  costUsd?: number | null;
  /** Providers attempted in order (last one succeeded) — fallback tracking. */
  providersTried: string[];
}

export interface RedesignProviderResult {
  bytes: Buffer;
  /** Provider-reported cost in USD, if the API returns it. */
  costUsd?: number | null;
}

export interface BalanceResult {
  /** Display string, e.g. "$4.60" or "free daily quota". */
  display: string;
  /** Numeric remaining balance in USD, or null if not applicable. */
  remaining: number | null;
}

/**
 * A provider's model-specific input requirements. The shared preprocessor reads
 * this and produces bytes that satisfy them — so a new model with its own needs
 * is integrated by declaring this object, NOT by writing resize code in the
 * provider. Omit a field to accept the shared-preprocess default.
 */
export interface InputSpec {
  /** Hard cap on the longest input edge in px (e.g. Cloudflare klein: 504). */
  maxEdge?: number;
  /** Output container the model expects. Default "image/jpeg". */
  format?: "image/jpeg" | "image/png";
  /** JPEG quality when re-encoding (default 90). */
  quality?: number;
}

export interface AiProvider {
  /** Stable id (persisted, shown in admin). */
  readonly key: string;
  /** Human-readable provider name. */
  readonly label: string;
  /** Model id/name this provider uses. */
  readonly model: string;
  /**
   * Model-specific input requirements applied by the shared preprocessor before
   * `redesign` is called. Omit for the shared default (1536px JPEG).
   */
  readonly inputSpec?: InputSpec;
  /** True when configured (keys present) and usable. Skipped if not ready. */
  isReady(): boolean;
  /**
   * Remaining balance/quota for the admin balance column. Optional — omit for
   * providers with no queryable balance. Never throws.
   */
  balance?(): Promise<BalanceResult>;
  /**
   * Run img2img. Returns the generated bytes plus provider-reported cost (if
   * the API exposes it). Throws on failure so the chain falls through.
   */
  redesign(req: RedesignRequest): Promise<RedesignProviderResult>;
}
