import "server-only";

import type { DesignStyle, RoomType } from "@/db/schemas/shared.schema";
import { preprocessForModel } from "./image-preprocess";
import { redesignWithFallback } from "./providers/registry";
import type { RedesignResult } from "./providers/types";

/*
 * AI redesign service — the entry point for image generation.
 *
 * Owns the PRIVATE prompt assembly (trade-secret — PROJECT_CONTEXT §12) and
 * delegates the actual generation to a provider chain (providers/registry.ts):
 * it tries each configured provider in order until one succeeds, and returns
 * which provider/model produced the result so it can be persisted on the design.
 *
 * Add/reorder/swap providers by editing providers/registry.ts — nothing here
 * changes.
 */

const RULES =
  "You are redesigning THIS actual room. Preserve the existing architecture " +
  "exactly: keep the real wall positions, window and door locations, ceiling " +
  "height, and room proportions. Only restyle furniture, decor, textiles, " +
  "lighting, and finishes. Photorealistic, same camera angle.";

// Style → BD-authentic direction, keyed by the DESIGN_STYLES enum. Kept private
// (trade-secret prompts — PROJECT_CONTEXT §12).
const STYLE_DIRECTION: Record<DesignStyle, string> = {
  modern:
    "warm modern middle-class Bangladeshi living space, rich wooden furniture " +
    "(Hatil/Otobi teak tones), large family seating, jute rugs, warm lighting.",
  traditional_bangla:
    "traditional Bengali heritage: carved dark wood, divan with bolster cushions, " +
    "terracotta and brass accents, nakshi kantha textiles.",
  minimal:
    "clean contemporary Dhaka apartment, neutral walls, comfortable large sofa " +
    "set, local wooden coffee table, subtle brass accents, warm daylight.",
  luxury:
    "upscale Bangladeshi interior, premium wood and marble, elegant large-family " +
    "seating, refined warm lighting, tasteful local motifs.",
  scandinavian:
    "light Scandinavian-influenced but liveable Dhaka home: pale woods, soft " +
    "neutral textiles, uncluttered warmth, practical family seating.",
  classic:
    "classic elegant Bangladeshi interior: timeless wooden furniture, symmetrical " +
    "layout, warm ambient lighting, refined but comfortable for a large family.",
};

function buildPrompt(style: DesignStyle, _roomType: RoomType, userPrompt?: string | null): string {
  const direction = STYLE_DIRECTION[style];
  const extra = userPrompt ? ` Additional request: ${userPrompt}.` : "";
  return `${RULES}\n\nRedesign as: ${direction}${extra}`;
}

export interface RedesignInput {
  imageBytes: Buffer;
  imageMime: string;
  /** Public URL of the uploaded source (used by URL-based providers). */
  imageUrl: string;
  style: DesignStyle;
  roomType: RoomType;
  userPrompt?: string | null;
}

export const AiService = {
  /**
   * Run img2img through the provider fallback chain. Returns the generated bytes
   * plus which provider/model produced them. Throws only if EVERY provider fails.
   */
  redesign: async (input: RedesignInput): Promise<RedesignResult & { inputBytes: number }> => {
    const prompt = buildPrompt(input.style, input.roomType, input.userPrompt);
    // Normalize the image ONCE here — every provider in the chain receives the
    // same model-ready bytes (providers must not preprocess). See image-preprocess.ts.
    const prepared = await preprocessForModel(input.imageBytes);
    const result = await redesignWithFallback({
      imageBytes: prepared.bytes,
      imageMime: prepared.mime,
      imageUrl: input.imageUrl,
      prompt,
      style: input.style,
      roomType: input.roomType,
    });
    return { ...result, inputBytes: prepared.bytes.length };
  },
};
