import "server-only";

import type { BudgetTier, DesignStyle, RoomType } from "@/db/schemas/shared.schema";
import { type ImageDims, preprocessForModel } from "./image-preprocess";
import { buildRedesignPrompt } from "./prompt";
import { redesignWithFallback } from "./providers/registry";
import type { RedesignResult } from "./providers/types";

/*
 * AI redesign service — the entry point for image generation.
 *
 * Delegates the PRIVATE prompt assembly to prompt.ts (trade-secret —
 * PROJECT_CONTEXT §12) and the generation to a provider chain
 * (providers/registry.ts): it tries each configured provider in order until one
 * succeeds, and returns which provider/model produced the result so it can be
 * persisted on the design.
 *
 * Add/reorder/swap providers by editing providers/registry.ts — nothing here changes.
 */

export interface RedesignInput {
  imageBytes: Buffer;
  imageMime: string;
  /** Public URL of the uploaded source (used by URL-based providers). */
  imageUrl: string;
  style: DesignStyle;
  roomType: RoomType;
  budget: BudgetTier;
  userPrompt?: string | null;
}

export const AiService = {
  /**
   * Run img2img through the provider fallback chain. Returns the generated bytes
   * plus which provider/model produced them. Throws only if EVERY provider fails.
   */
  redesign: async (
    input: RedesignInput,
  ): Promise<RedesignResult & { inputDims: ImageDims; prompt: string }> => {
    const prompt = buildRedesignPrompt({
      style: input.style,
      roomType: input.roomType,
      budget: input.budget,
      userPrompt: input.userPrompt,
    });
    // Normalize the image ONCE here — every provider in the chain receives the
    // same model-ready bytes (providers must not preprocess). See image-preprocess.ts.
    const prepared = await preprocessForModel(input.imageBytes);
    const result = await redesignWithFallback({
      imageBytes: prepared.bytes,
      imageMime: prepared.mime,
      imageUrl: input.imageUrl,
      prompt,
      style: input.style,
      roomType: input.roomType,
    });
    return { ...result, inputDims: prepared.dims, prompt };
  },
};
